pages:
  image: registry.gitlab.com/systemkern/s5:latest 
  stage: deploy
  script:
    - ls -al
    - ls -al public
    - lftp -u $FTP_USER,$FTP_PASS $SERVER:$PORT '
      set net:timeout 5;
      set net:max-retries 1;
      mirror -R public .
      '
  artifacts:
    paths:
    - public
#  only:
#    - master

