image: alpine

pages:
  stage: build
  script:
    - ls -al public
    - echo "Deploying to gitlab pages rainerkern.gitlab.io/www-rainerkern-at"
  artifacts:
    paths:
      - public
  only:
    - master
